In [1]:
import math
import numpy as np

In [21]:
profit = np.array([[24, 70, 41, 21, 60], [47, 82, 87, 80, 35], [73, 89, 100, 90, 17], [77, 83, 85, 79, 55], [12, 27, 52, 15, 30]], dtype=np.float32)
profit *= 7500

hunters = np.array([[2, 4, 3, 2, 4], [3, 5, 5, 5, 3], [4, 5, 8, 7, 2], [5, 5, 5, 5, 4], [2, 3, 4, 2, 3]], dtype=np.float32)
players = np.array([[0, 100/4, 0, 0, 0], [0, 0, 100/4, 0, 0], [100/4, 100/4, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0],], dtype=np.float32)


profit /= (hunters)

print(120000 * 3 - 100000)

for row in profit:
    print(row)

260000
[ 90000. 131250. 102500.  78750. 112500.]
[117500. 123000. 130500. 120000.  87500.]
[136875.   133500.    93750.    96428.57  63750.  ]
[115500. 124500. 127500. 118500. 103125.]
[45000. 67500. 97500. 56250. 75000.]
